package com.builtin.model;

public enum ItemCategory {
    SEALING_AND_ADHESIVES,
    PAINTS_SPRAYS_CLEANING,
    CUTTING_AND_GRINDING,
    POLISHING_AND_SANDING,
    CERAMICS_AND_TILING,
    PLASTERBOARD,
    CEMENT_AND_ADHESIVES,
    IRON_AND_METAL
}
