# Server
server.port=8081

# App
spring.application.name=builtin-webapp

# Freemarker
spring.freemarker.template-loader-path=classpath:/templates/
spring.freemarker.suffix=.ftlh
spring.freemarker.cache=false
spring.freemarker.charset=UTF-8

# Backend API base URL
backend.api.base-url=http://localhost:8080/api

# i18n
spring.messages.basename=messages
spring.messages.encoding=UTF-8
spring.messages.fallback-to-system-locale=false
